import Layout from '@/components/PageLayout/Layout'
import { useEffect } from 'react'
import { handleScripts } from '../js/init'
import Head from 'next/head'
import '@/styles/globals.css'
import '@/styles/plugins.css'

export default function App({ Component, pageProps }) {

  useEffect(() => { handleScripts() })

  return (
    <Layout>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </Layout>
  )
}
