import Head from 'next/head'
import MobileMenu from '@/components/MobileMenu'
import Header from '@/components/Header'
import MainPart from '@/components/MainPart'
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="cavani_tm_all_wrap" data-magic-cursor="show" data-enter="bounceIn" data-exit="">
        <MobileMenu />
        <Header />
        <MainPart />
        <Footer />
      </div>
    </>
  )
}
